name: knoma create indices

on:
  push:

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - name: checkout repo
     uses: actions/checkout@v2.3.4
     with:
       token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
   - name: knoma create indices
     uses: oli4jansen/knoma-create-indices-github-action@v0.3
   - name: commit to repo
     uses: EndBug/add-and-commit@v9
     with:
       default_author: github_actions
       message: 'knoma automatically updated indices'
